import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import { useState } from "react";
import { getUsers } from "./api/auth";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [inputField, setInputField] = useState({
    email: '', password: ''
  })
  const [error, setError] = useState('');
  const router = useRouter();

  const validateEmail = (email) => {
    console.log(email, "email")
    const re = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return re.test(email);
  };

  const validatePassword = (password) => {
    return password.length >= 6;
  };

  const handleOnClick = async () => {
    if (!validateEmail(inputField.email)) {
      setError('Invalid email format.');
      return;
    } else if (!validatePassword(inputField.password)) {
      setError('Password must be at least 6 characters long.');
      return;
    } else {
      router.push('/dashboard');
    }
  }
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started with Vinoba's Fintech project <br /><br /> Please Log-In
          </p>
        </div>

        <div className={styles.center}>
          <div className={styles.centerCard}>
            <h1>Log-In</h1>
            <br />
            <br />
            <label>Email</label>
            <br /><br />
            <input className={styles.inputField} name="email" type="email" onChange={(e) => setInputField({ ...inputField, email: e.target.value })} />
            <br />
            <br />
            <label>Password</label>
            <br /><br />
            <input className={styles.inputField} name="pasword" type="password" onChange={(e) => setInputField({ ...inputField, password: e.target.value })} />
            <br /> <br />
            <div className={styles.card} onClick={handleOnClick}>
              LogIn <span>-&gt;</span>
            </div>
            {error && <p className={styles.error}>{error}</p>}
          </div>
        </div>

        <div>Fintech &#169; 2024</div>
      </main>
    </>
  );
}
